//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSyncWeb
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/CRMSyncWeb")]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        private bool isClientErrorField;
        
        private string errorMessageField;
        
        private string dataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool isClientError
        {
            get
            {
                return this.isClientErrorField;
            }
            set
            {
                this.isClientErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payload", Namespace="http://schemas.datacontract.org/2004/07/CRMSyncWeb")]
    public partial class Payload : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid idField;
        
        private string xmlStringField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string xmlString
        {
            get
            {
                return this.xmlStringField;
            }
            set
            {
                this.xmlStringField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICRMSyncService")]
public interface ICRMSyncService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/getUser", ReplyAction="http://tempuri.org/ICRMSyncService/getUserResponse")]
    CRMSyncWeb.Result getUser(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/getUser", ReplyAction="http://tempuri.org/ICRMSyncService/getUserResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> getUserAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/createUser", ReplyAction="http://tempuri.org/ICRMSyncService/createUserResponse")]
    CRMSyncWeb.Result createUser(CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/createUser", ReplyAction="http://tempuri.org/ICRMSyncService/createUserResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> createUserAsync(CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/updateUser", ReplyAction="http://tempuri.org/ICRMSyncService/updateUserResponse")]
    CRMSyncWeb.Result updateUser(string id, CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/updateUser", ReplyAction="http://tempuri.org/ICRMSyncService/updateUserResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> updateUserAsync(string id, CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/deleteUser", ReplyAction="http://tempuri.org/ICRMSyncService/deleteUserResponse")]
    CRMSyncWeb.Result deleteUser(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/deleteUser", ReplyAction="http://tempuri.org/ICRMSyncService/deleteUserResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> deleteUserAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/getBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/getBusinessResponse")]
    CRMSyncWeb.Result getBusiness(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/getBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/getBusinessResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> getBusinessAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/creatBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/creatBusinessResponse")]
    CRMSyncWeb.Result creatBusiness(CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/creatBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/creatBusinessResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> creatBusinessAsync(CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/updateBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/updateBusinessResponse")]
    CRMSyncWeb.Result updateBusiness(string id, CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/updateBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/updateBusinessResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> updateBusinessAsync(string id, CRMSyncWeb.Payload payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/deleteBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/deleteBusinessResponse")]
    CRMSyncWeb.Result deleteBusiness(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMSyncService/deleteBusiness", ReplyAction="http://tempuri.org/ICRMSyncService/deleteBusinessResponse")]
    System.Threading.Tasks.Task<CRMSyncWeb.Result> deleteBusinessAsync(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICRMSyncServiceChannel : ICRMSyncService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CRMSyncServiceClient : System.ServiceModel.ClientBase<ICRMSyncService>, ICRMSyncService
{
    
    public CRMSyncServiceClient()
    {
    }
    
    public CRMSyncServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CRMSyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CRMSyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CRMSyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CRMSyncWeb.Result getUser(string id)
    {
        return base.Channel.getUser(id);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> getUserAsync(string id)
    {
        return base.Channel.getUserAsync(id);
    }
    
    public CRMSyncWeb.Result createUser(CRMSyncWeb.Payload payload)
    {
        return base.Channel.createUser(payload);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> createUserAsync(CRMSyncWeb.Payload payload)
    {
        return base.Channel.createUserAsync(payload);
    }
    
    public CRMSyncWeb.Result updateUser(string id, CRMSyncWeb.Payload payload)
    {
        return base.Channel.updateUser(id, payload);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> updateUserAsync(string id, CRMSyncWeb.Payload payload)
    {
        return base.Channel.updateUserAsync(id, payload);
    }
    
    public CRMSyncWeb.Result deleteUser(string id)
    {
        return base.Channel.deleteUser(id);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> deleteUserAsync(string id)
    {
        return base.Channel.deleteUserAsync(id);
    }
    
    public CRMSyncWeb.Result getBusiness(string id)
    {
        return base.Channel.getBusiness(id);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> getBusinessAsync(string id)
    {
        return base.Channel.getBusinessAsync(id);
    }
    
    public CRMSyncWeb.Result creatBusiness(CRMSyncWeb.Payload payload)
    {
        return base.Channel.creatBusiness(payload);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> creatBusinessAsync(CRMSyncWeb.Payload payload)
    {
        return base.Channel.creatBusinessAsync(payload);
    }
    
    public CRMSyncWeb.Result updateBusiness(string id, CRMSyncWeb.Payload payload)
    {
        return base.Channel.updateBusiness(id, payload);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> updateBusinessAsync(string id, CRMSyncWeb.Payload payload)
    {
        return base.Channel.updateBusinessAsync(id, payload);
    }
    
    public CRMSyncWeb.Result deleteBusiness(string id)
    {
        return base.Channel.deleteBusiness(id);
    }
    
    public System.Threading.Tasks.Task<CRMSyncWeb.Result> deleteBusinessAsync(string id)
    {
        return base.Channel.deleteBusinessAsync(id);
    }
}
